### ISSUE TITLE
Stopping crowd starts another JVM with the same JAVA_OPTS

### ISSUE THREAD

**Issue by galcorlo** [joshbeard/puppet-crowd#14]
We should use CATALINA_OPTS to configure java boot options instead of JAVA_OPTS. Otherwise when we stop the process it starts another JVM with the same memory required for Crowd. This amount of memory could be too much and it's not necessary.

More info:
http://www.tikalk.com/java/when-use-tomcat-catalinaopts-instead-javaopts/

**Comment by joshbeard** [comment]
Thanks, how does https://github.com/joshbeard/puppet-crowd/compare/master...joshbeard:catalina_opts?expand=1 look?
