### ISSUE TITLE
crowd.service.erb issue

### ISSUE THREAD

**Issue by jtaylor28** [joshbeard/puppet-crowd#2]
Hi Josh,

First off, thanks for forking and further developing the actionjack crowd module.

I'm currently using your module with RedHat 7, however after successfully installing Crowd and setting up a postgresql database to back it with, the service does not start. After some investigation, it turns out that the crowd.service.erb template is pointing to the wrong PID file (in the case of RedHat 7). This is because the following file does not exist in the said directory:

PIDFile=<%= scope.lookupvar('crowd::app_dir') %>/apache-tomcat/work/catalina.pid

Therefore changing the template to point to the following file works perfectly and the service then starts:

PIDFile=<%= scope.lookupvar('crowd::app_dir') %>/apache-tomcat/work/crowd.pid

Would it be possible for you to alter this in the module? Or would you prefer me to make a pull request?

Thanks in advance,
Jordan

**Comment by joshbeard** [comment]
Whoops!  Thanks.  Corrected in e3b0f6787f8bb09041a2c2d0c0aaceb245e7669b and released 1.0.1 https://forge.puppetlabs.com/joshbeard/crowd/1.0.1/readme
