### ISSUE TITLE
Wrong Init Script on Debian Stretch

### ISSUE THREAD

**Issue by waza-ari** [joshbeard/puppet-crowd#20]
When using this module (version 1.0.5) under Debian Stretch (9), the init script does not work out of two reasons:

```
# Source function library
. /etc/rc.d/init.d/functions
```

I think in Debian this should be `. /lib/lsb/init-functions`. When changing this, it works.

Further, the "daemon" package is not installed by default in Debian, hence the following line

```
systemctl status crowd.service
```

does not work as well. Installing the `daemon` package and changing the option described above works. I'm neither very familiar with puppet nor with start scripts, so I cannot really help except with testing...

**Comment by joshbeard** [comment]
Hi, this may be addressed in https://github.com/joshbeard/puppet-crowd/commit/e58bc7eb139ce47fff8c8a450413032eb6580e8b#diff-2f383a197b1a428561b364755701d60e

Can you confirm?

**Comment by joshbeard** [comment]
The latest Forge release has changes to the system configuration (version 1.1.1)

**Comment by waza-ari** [comment]
Hey joshbeard,

Thanks for your work! Unfortunately I’m not using the Atlassian suite anymore and hence not using this puppet module anymore. I will not be able to test, I’m sorry...
