### ISSUE TITLE
nologin shell

### ISSUE THREAD

**Issue by AdamJacobMuller** [joshbeard/puppet-crowd#3]
Hello,
On Ubuntu 14.04 LTS (at least) `nologin` is located at `/usr/sbin/nologin` not `/sbin/nologin`.

It is hard-coded to `/sbin/nologin`: https://github.com/joshbeard/puppet-crowd/blob/master/manifests/init.pp#L24

I can (and might even) submit a patch/PR for it later, but, wanted to file a bug report before I forget.

**Comment by joshbeard** [comment]
This should be solved in 1.0.2 via commit 2626644
