### ISSUE TITLE
Let Tomcat only listen on local connections

### ISSUE THREAD

**Issue by ronaldvanrij** [joshbeard/puppet-crowd#4]
I am looking for a method to let Tomcat only listen to local connections, since I'll be running Crowd behind a proxy to do SSL. The setting can be configured in the server.xml file. Any chance of having this included, or would you like me to create a pull request?

**Comment by ronaldvanrij** [comment]
Apparently one can also use the `proxy` parameter to set any additional attributes in the server.xml's Connector. Like so:
```
proxy => {
  address => "127.0.0.1"
}
```

**Comment by joshbeard** [comment]
Does this provide the functionality you were looking for, or is there any need for modification of this module?

**Comment by ronaldvanrij** [comment]
Yes, this workaround does provide the functionality I need. Except for the fact it is a workaround as the parameter "address" is should not be part of the proxy section. I see three options:

1. Leave as-is and let the proxy hash be used for any Connector setting
2. Rename "proxy" to something like "tomcatConnector", or add a "tomcatConnector" parameter
3. Add specific parameters for "tomcatAddress" and "tomcatPort"

I'd prefer option 3, as this method is also used in the puppet-jira module.

**Comment by joshbeard** [comment]
Hi, I've added a `tomcat_address` parameter in 1.1.0, which provides what you're looking for:

https://forge.puppet.com/joshbeard/crowd/1.1.0/changelog

There's also an existing `tomcat_port` parameter to configure the connector's port.
