### ISSUE TITLE
Using the default for download_url doesn't work

### ISSUE THREAD

**Issue by SyBernot** [joshbeard/puppet-crowd#5]
not setting download_url results in 
Error: curl  -f -L -o /opt/staging/crowd/atlassian-crowd-2.8.4.tar.gz https://www.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.8.4.tar.gz/atlassian-crowd-2.8.4.tar.gz returned 22 instead of one of [0]

if you however set download_url to 'https://www.atlassian.com/software/crowd/downloads/binary/' it works fine.

**Comment by joshbeard** [comment]
Thanks.  Should be resolved by 344ef545644e82f3d220aaab1a5607b41eceff8b and part of [1.0.4](https://forge.puppetlabs.com/joshbeard/crowd/1.0.4/readme)
