### ISSUE TITLE
dependency: nanliu-staging vs. puppet-staging

### ISSUE THREAD

**Issue by bhundven** [joshbeard/puppet-crowd#7]
I'm also using puppet-jira and puppet-confluence, which depend on puppet-staging. Is there a specific reason for using nanliu-staging over puppet-staging?

**Comment by joshbeard** [comment]
No, the dependency list is just outdated.  I'll get that updated.  puppet-staging should work fine manually in the meantime.

**Comment by joshbeard** [comment]
Updated in 159f8dee6d965568107ccd753585dd58cfc3de30
Released 1.0.5: https://forge.puppet.com/joshbeard/crowd/1.0.5/readme
